title: Mickey Graf
description: Production AI systems
url: https://mikigraf.github.io
baseurl: ""
markdown: kramdown
permalink: /:year/:month/:day/:title/
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
